// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Naruto Volume 70",
    url: "https://879ed873-madman-com-au.akamaized.net/media/Releases/32701/32701-1026236.jpg",
    originalPrice: 29.95,
    salePrice: 14.95,
    rating: 4.5,
    description: "In order to face off against Madara and his newly acquired Six Paths power, Guy pulls out his most dangerous move. Guy has put his very life on the line, but is it enough against Madara? Meanwhile, as Naruto fights on the edge of death, he meets a special figure who may change the entire direction of the battle!",
    classification: 	
    'Release Date: 10/07/2015,  Author: Masahi Kishimoto, Number of Pages: 70, Issue: 192 (Ongoing), Classification Teen 13+.',   
  },
  {
    id: 2,
    title: "One Piece Volume 96",
    url: "https://879ed873-madman-com-au.akamaized.net/media/Releases/58362/58362-2276181.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
    description: "As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his life changed when he accidentally gained the power to stretch like rubber...at the cost of never being able to swim again! Years, later, Luffy sets off in search of the One Piece, said to be the greatest treasure in the world. During his journey with Whitebeard’s crew, Oden encounters the legendary future pirate king Gold Roger! What does their meeting mean for the world? And what has Orochi been up to while Oden was gone from Wano?!",
    classification: " Release Date: 11/06/2021, Author: Eiichiro Oda,  Number of Pages: 200, Issue: 96 (Ongoing), Classification Teen 13+.",
  },
  {
    id: 3,
    title: "Vinland Saga Volume 21",
    url: "https://images-na.ssl-images-amazon.com/images/I/91OAkkE-2qL.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
    description: "Thanks to his claim by lineage, the attackers surrounding Jomsborg want Thorfinn to be their leader, but it is a mantle he intensely rejects. When the battle for leadership over the powerful Jomsvikings reaches a stalemate, Thorfinn must make a critical decision. With Gudrid held captive within the fortressed city, walking away will not be an option. He must infiltrate Jomsborg to break her out, and the ensuing battle will leave the greatest mercenary force in the North Sea changed forever...",
    classification: "Release Date: 17/12/2019, Author: Makoto Yukimura, Issue: 21 (Ongoing), Classification Teen 18+.",
  },
  {
    id: 4,
    title: "Death Note Volume 1",
    url: "https://upload.wikimedia.org/wikipedia/en/6/6f/Death_Note_Vol_1.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
    description: "Any human whose name is written in the notebook dies, and now Light has vowed to use the power of the Death Note to rid the world of evil. But when criminals begin dropping dead, the authorities send the legendary detective L to track down the killer.",
    classification: "Release Date: 28/12/2010, Author: Makoto Yukimura, Issue: 2, Classification Teen 16+.",
  },
  {
    id: 5,
    title: "Steel Ball Run Volume 2",
    url: "https://i.imgur.com/iDwCq3Uh.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
    description: "As the racers cut through the Mexican wind, Gyro glances behind him as he sees Pocoloco and the other racers are catching up to him. Johnny and Diego Brando are evenly matched but Johnny is determined to take the lead. Meanwhile, the horses of some racers have reached their limits and begin collapsing from exhaustion. Diego realizes that his technique is useless and he will have to rely on the horse's leg power. As Hey Ya! tells Pocoloco that he should go left, Sandman rejoins the lead group and sprints past both Pocoloco and Gyro. Who will come out on top?",
    classification: "Author: Hirohiko Araki, Issue: 2 (Ongoing), Classification Teen 18+."
  },
  {
    id: 6,
    title: "Demon Slayer Volume 17",
    url: "https://i.pinimg.com/originals/b1/fe/0a/b1fe0a8a644ae3effb91617fe44c68a2.jpg",
    originalPrice: 22.00,
    salePrice: 12.5,
    rating: 5,
    description: "The Demon Slayer Corps plunges into Infinity Castle to confront Muzan. Shinobu engages in a fierce fight against Doma, the Upper Rank 2 demon. Poison doesn't work on him, so she finds herself in an intense struggle. Will she be able to defeat the demon who killed her older sister?!",
    classification: "Author: Koyoharu Gotouge, Issue: 17, Classification Tween 12+.",
  },
  {
    id: 7,
    title: "Dr Stone Volume 1",
    url: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781974702619/dr-stone-vol-1-9781974702619_hr.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
    description: "One fateful day, all of humanity turned to stone. Many millennia later, Taiju frees himself from the petrification and finds himself surrounded by statues. The situation looks grim—until he runs into his science-loving friend Senku! Together they plan to restart civilization with the power of science!",
    classification: "Author: Koyoharu Gotouge, Issue: 1 (ongoing), Classification Tween 12+."
  },
  {
    id: 8,
    title: "Billy Bat Volume 1",
    url: "https://images-na.ssl-images-amazon.com/images/I/81mQxtsh6cL.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
    description: "The story begins in 1949 and follows Japanese-American comic book artist Kevin Yamagata as he draws the popular detective series Billy Bat. When he learns he may have unconsciously copied the character from an image he saw while serving in occupied Japan, he returns to Japan to get permission to use Billy Bat from its original creator. Upon arriving there, however, he becomes embroiled in a web of murder, cover-ups, and prophecy that all leads back to Billy Bat.",
    classification: "Author: Naoki Urasawa, Issue: 1, Number of Pages: 65, Classification Teen 18+."
  },
  {
    id: 9,
    title: "Fire Force Volume 2",
    url: "https://i.pinimg.com/736x/a7/80/d2/a780d255aa0ea26f238f108f7796fdca.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
    description: "A mysterious man has crashed the Rookie Games, and he did it all for Shinra! Does he really know the truth behind the fire that took Shinra's family 12 years ago? And will Shinra decide to be a hero, or will this man's shocking revelation tempt him to become a real devil?",
    classification: "Author: Ohkubo, Atsushi, Issue: 2, Number of Pages: 50, Classification Teen 14+."
  },
  {
    id: 10,
    title: "Pluto Volume 2",
    url: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781421519197/pluto-urasawa-x-tezuka-vol-2-9781421519197_hr.jpg",
    originalPrice: 30,
    salePrice: null,
    rating: 5,
    description: "In an ideal world where man and robots coexist, someone or something is after the seven great robots of the world. Interpol assigns robot detective Gesicht to this most strange and complex case--and he eventually discovers that he is one of the targets!",
    classification: "Author: Naoki Urasawa, Issue: 2, Classification Teen 17+.",
  },
  {
    id: 11,
    title: "Dragon Ball Super Volume 14",
    url: "https://cdn.shopify.com/s/files/1/0882/5118/products/VIZ_MEDIA-Dragon_Ball_Super_Vol_14_Manga-2529965_1024x1024.jpg?v=1630010085",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
    description: "The struggle against Moro and the fight for the fate of the Earth continues. Vegeta finally returns from planet Yardrat and asks Goku to step aside so he can face the evil space wizard alone. But something is different about Vegeta since his training with the mysterious Yardratians, and his attacks seem to be working to weaken Moro! Will Vegeta's training be enough to step out of Goku's shadow and end this battle once and for all?",
    classification: "Author: Akira Toriyama , Issue: 14 (ongoing), Classification Teen 14+.",
  },
  {
    id: 12,
    title: "Bleach Volume 49",
    url: "https://images-na.ssl-images-amazon.com/images/I/81JTNoJKKaL.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
    description: "Ichigo Kurosaki never asked for the ability to see ghosts—he was born with the gift. When his family is attacked by a Hollow—a malevolent lost soul—Ichigo becomes a Soul Reaper, dedicating his life to protecting the innocent and helping the tortured spirits themselves find peace. fter a long battle, Ichigo loses his Soul Reaper powers... Ichigo now leads a quiet and peaceful life until he is approached by a mysterious man. What does the man want and how does it relate to Ichigo's lost powers?!",
    classification: "Author: Tite Kubo , Issue: 49, Classification Teen 14+.",
  },
];